export const FEATCH_CRYTO_CURRENCIES_REQUEST = 'FEATCH_CRYTO_CURRENCIES_REQUEST';
export const FEATCH_CRYTO_CURRENCIES_SUCCESS = 'FEATCH_CRYTO_CURRENCIES_SUCCESS';
export const FEATCH_CRYTO_CURRENCIES_FAILURE = 'FEATCH_CRYTO_CURRENCIES_FAILURE';
