export const ACTION_NAMES = {
  INCREMENT: 'increment',
  DECREMENT: 'decrement',
  LOGIN: 'login',
  LOGOUT: 'logout',
  ADD_TO_CART: 'ADDTOCART',
  UPDATE_PAGE_NAME: 'UPDATEPAGENAME',
  DELETE_CURRENCY: 'DELETECURRENCY'
};
